on:
  push:
    branches:
      - master
      - migrant

name: Deploy to ShinyApps

jobs:
  Deploy:
    runs-on: ubuntu-22.04

    name: Deploy to ShinyApps

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node 19.5.0
        uses: actions/setup-node@v3
        with:
          node-version: '19.5.0'
          architecture: 'x64'
          cache: 'yarn'
          cache-dependency-path: 'Client/yarn.lock'

      - name: Build UI
        run: |
          npm install -g yarn
          yarn set version latest
          yarn install
          yarn build
        working-directory: Client

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.2'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"'
          pak-version: devel
          extra-packages: |
            any::rsconnect
            any::pkgbuild
            any::rcmdcheck
          working-directory: Server

      - name: Install hivPlatform R package
        run: |
          pak::pkg_install('github::nextpagesoft/hivEstimatesAccuracy2/Server@migrant')
        shell: Rscript {0}
        working-directory: Server

      - name: Deploy
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
          SHINYAPPS_APP_NAME: hivPlatform-${{ env.GITHUB_REF_NAME }}
        run: >
          rsconnect::setAccountInfo(
            name   = Sys.getenv('SHINYAPPS_ACCOUNT'),
            token  = Sys.getenv('SHINYAPPS_TOKEN'),
            secret = Sys.getenv('SHINYAPPS_SECRET')
          );
          rsconnect::deployApp(
            account = Sys.getenv('SHINYAPPS_ACCOUNT'),
            appName = 'hivPlatform-migrant',
            appFiles = 'app.R',
            contentCategory = 'application',
            forceUpdate = TRUE
          )
        shell: Rscript {0}
        working-directory: Server
